= Pflichtenheft
:project_name: Festivalmanager
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2021          | Autor       | Initiale Version
|0.2     | In Arbeit   | 26.10.2021          | Georg, Jan, Ahmad
       | -
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

In diesem Dokument werden die wichtigsten Informationen zum Projekt sowohl 
für die Entwickler als auch für den Auftraggeber zusammengefasst.
Vor allem werden hier Anforderungen an das Produkt festgehalten, auf die 
sich Entwickler und Auftraggeber geeinigt haben. Einige Konkrete Ansätze für die
Implementation sind in den Abschnitten zum GUI Prototyp und Datenmodell zu finden.
Am Ende der Enticklung kann dieses Dokument verwendet werden, um zu prüfen, ob 
das Produkt den Anforderungen des Auftraggebers entspricht.

Ein besonders wichtiger Unterpunkt sind die Anwendungsfälle der Software,
die den Entwicklern als Grundlage für die GUI und das Klassendiagramm dienen.
Im Abschnitt zu funktionalen Anforderungen werden Muss- und Kann Kriterien zusammengetragen,
die der Festivalmanager am Ende der Entwicklung unbedingt erfüllen muss bzw. zusätzlich erfüllen kann.
Im Unterpunkt "Systemgrenze und TLA" werden noch Erkenntnisse aus der
Analysephase per UML visualisiert.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

Der Festivalveranstalter, die „FVIV GmbH“, sieht sich mit ihrem derzeitigen System den wachsenden 
Aufgaben einer Festival-Organisation und –Durchführung nicht mehr gewachsen und benötigt daher 
zeitnah ein neues IT-System, das interne Verwaltungsaufgaben, als auch den Kundenkontakt 
übernimmt. Daher werden sie damit beauftragt, dieses System zu entwerfen und auch umzusetzen.

Das System soll unter anderem in der Planungsabteilung eingesetzt werden, in der Festivals angelegt 
werden.  Dazu  muss  ein  Termin  festgelegt  werden  und  die  passende  Location  zu  diesem  Zeitpunkt  
gebucht werden. Doppelbuchungen dieser Locations sind unter allen Umständen zu vermeiden. Jede 
Location  bietet  Platz  für  eine  maximale  Anzahl  von  Besuchern  und  Bühnen.  Außerdem  ist  jede  
Location  in  verschiedene,  eindeutig  gekennzeichnete  Bereiche  unterteilt,  die  wiederum  einen  Teil  
der  maximalen  Besucherzahl  fassen  können  und  sich  außerdem  in  Camping-,  Park-,  Catering-  und 
Stage-Bereiche  einordnen.  Um  dem  Planungsteam  einen  guten  Überblick  zu  verschaffen,  ist  es  
zwingend  notwendig,  dass  das  Gelände  und  die  Bereiche  visualisiert  werden  können.  Sobald  die  
Location gebucht ist, können für dieses Festival Anpassungen durchgeführt werden, wie die 
Bühnenpositionierung, Toilettenbestückung und Cateringstände, und es muss möglich sein, 
bestimmte  Bereiche  zu  sperren.  Die  genannten  Gegenstände  (Bühnen,  usw.)  werden  von  externen  
Anbietern gemietet.

In  der  nächsten  Stufe  muss  das  „Line-Up“  zusammengestellt  werden.  Dazu  müssen  Angebote  bei  
verschiedenen  Künstlern  eingeholt  werden.  Anschließend  werden  aus  diesen  Angeboten  Künstler  
ausgewählt  und  es  muss  ein  Spielplan  für  jede  Bühne  erstellt  werden.  Neben  den  genannten  
Künstlern  ist  weiteres  Personal  erforderlich,  wie  Sicherheitspersonal  (mindestens  einer  pro  100  
Besuchern),  Bedienungen  an  den  Cateringständen,  Bühnentechniker  (Anzahl  wird  durch  die  Band  
bestimmt), sowie ein Veranstaltungsleiter. Jede Arbeitskraft wird dabei auf Stundenbasis bezahlt.

Zu  jedem  Zeitpunkt  während  der  Planung  muss  der  Planungsabteilung  als  auch  dem  Management  
eine  automatische  Kostenaufstellung  zur  Verfügung  gestellt  werden  können,  in  der  Kosten  für  
Mieten, Gagen, Personal und Sonstigem aufgelistet und aggregiert werden.

Schon während der Planungsphase kann ein Event freigegeben werden, und es kann ein Kartenpreis 
festgelegt  werden.  Es  gibt  dabei  Camping-Tickets,  die  das  ganze  Festival  über  gültig  sind und  
Tageskarten.  Diese  Tickets  werden  bis  3  Tage  vor  Veranstaltungsbeginn  in  den  Filialen  der  „FVIV  
GmbH“ verkauft und danach nur noch an der Abendkasse. Es muss den Verkaufsmitarbeitern möglich 
sein, bei noch vorhandenen Tickets diese zu verkaufen und auszudrucken. Auf jedes Ticket wird ein 
Barcode  bzw.  eine  eindeutige  Nummer  aufgedruckt,  mit  dem  es  dem  Personal  am  Festivaleingang  
möglich  ist,  das  Ticket  auf  Gültigkeit  hin  zu  überprüfen  und  zu  vermeiden,  dass  verschiedene  
Personen das Gelände mit derselben Karte betreten. 

Eine  weitere  Nutzergruppe  ist  das  Cateringpersonal,  das  sich  an  entsprechenden  Terminals  am 
Verkaufsstand mit gültigem Login anmeldet. Dort können Getränke und vorgefertigte Speisen 
ausgewählt  und  abgerechnet  werden.  Dabei  wird  das  Gekaufte  vom  verfügbaren  Lagerbestand  
abgezogen. Sollte ein gewisser Mindestbestand unterschritten werden erfolgt eine Mittteilung an die 
Festivalleitung.

Der  Festivalleiter  besitzt  ebenfalls  ein  persönliches  Terminal,  an  dem  es  ihm  möglich  ist,  das  Lager  
einzusehen  und  Nachbestellungen  zu  tätigen.  Weiterhin  sieht  er  dort  aktuelle  Besucherzahlen,  
Nachrichten von anderen Mitarbeitern, sowie Verkaufszahlen des Caterings und die aktuelle 
Bühnenbelegung.

Überall auf dem Festivalgelände verteilt befinden sich Terminals, die für jeden frei nutzbar sind. Dort 
sieht man neben einem Plan vom Festivalgelände auch den Spielplan für alle Festivaltage.

Der Manager der „FVIV GmbH“ sorgt für die Verteilung der Logins an die Mitarbeiter und kann sehen, 
welcher  Mitarbeiter  momentan  am  System  angemeldet  ist.  Weiterhin  soll  es  ihm  möglich  sein, 
betriebswirtschaftliche Daten, wie Umsatz, Ausgaben,... , abzurufen und grafisch zu visualisieren


Zum Abschluss des Projekts ist unser oberste Ziel natürlich, alle obigen Anforderungen zu erfüllen.

Dabei ist es wichtig, dass das Programm eine intuitive Benutzeroberfläche hat und ohne langer 
Einarbeitunszeit benutzt werden kann.
Wir wollen außerdem stabile Software bauen, welche nicht bspw. das Cateringpersonal 
bei einer invaliden Eingabe durch einen Absturz ausbremst.
Unsere Software sollte für die Organisation von 10 Festivals pro Jahr genauso gut wie 
für die Organisation von 100 Festivals pro Jahr geeignet sein,
um Wachstum der „FVIV GmbH“ nicht zu behindern.

Der Programmcode des Festivalmanagers sollte so geschrieben werden, dass er bei zukünftigen
Projekten teilweise wiederverwendet werden kann.
Unser Code sollte leicht instandzuhalten und zu erweitern sein.
Beim Abschluss des Projekts sollte unser Code also gut lesbar sein, 
wenig Codeverschmutzung aufweisen und gründlich dokumentiert sein.

== Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen

== Interessensgruppen (Stakeholders)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name |Beschreibung
|Besucher |Ein Festivalbesucher, kann Terminals nutzen um den Lageplan und Zeitplan abzurufen
|Personal |Personal des Festivalls
|Catering-Personal |Verkäufer von Speisen und Getränken, kann den Festivalleiter über geringe Lagerbestände informieren
|Security-Personal |sorgt für Sicherheit auf dem Gelände
|Einlass-Personal |kontrolliert Tickets am Eingang
|Festivalleiter |kann Lager überprüfen und Nachbestellung tätigen, empfängt Nachrichten vom Personal
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Ticketverkauf
|Beschreibung                |bis 3 Tage vor Eventbegin sollen Tickets gekauft werden können. Dabei wird in Camping und Tagestickets unterschieden. Alle Teckits haben eine eindeutige Nummer, die für die Eingangskontrolle verwendet wird.
|Akteure                     |Ticket-Verkäufer, Besucher
|Auslöser                    |Ein Besucher möchte ein Ticket kaufen
|Voraussetzung(en)           a|
1. Es sind noch Tickets vorhanden
2. Das Ticket wird mindestens 3 Tage  vor Event begin verkauft
|Essentielle Schritte        a|
1. Auswahl zwischen Camping und Tagesticket
2. Generierung einer eindeutigen Nummer für das Ticket
3. Abfrage des Ticketpreises (abhängig vom Ticket-Typ und Event)
4. Verkauf des Tickets (Verkäufer verlang Geld)
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Abendkasse-Ticketverkauf
|Beschreibung                |ab 3 Tagen vor Eventbegin sollen Tickets an der Abendkasse gekauft werden können. Dabei wird in Camping und Tagestickets unterschieden. Alle Teckits haben eine eindeutige Nummer, die für die Eingangskontrolle verwendet wird.
|Akteure                     |Ticket-Verkäufer, Besucher
|Auslöser                    |Ein Besucher möchte ein Ticket kaufen
|Voraussetzung(en)           a|
1. Es sind noch Tickets vorhanden
2. Das Ticket wird ab 3 Tagen  vor Event begin verkauft
|Essentielle Schritte        a|
1. Auswahl zwischen Camping und Tagesticket
2. Generierung einer eindeutigen Nummer für das Ticket
3. Abfrage des Ticketpreises (abhängig vom Ticket-Typ und Event)
4. Verkauf des Tickets (Verkäufer verlang Geld)
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Eingangskontrolle
|Beschreibung                |Am Eingang zu der Location, auf der Ein Event stattfindet werden die Tickets der Besucher kontrolliert
|Akteure                     |Sicherheits-Personal, Besucher
|Auslöser                    |Ein Besucher möchte das Festival-Gelände betreten
|Voraussetzung               |Es läuft gerade ein Festival an dieser Location
|Essentielle Schritte        a|
1. Ablesen der Ticketnummer
2. Abfrage ob die Ticketnummer für dieses Event gültig ist
3. Ticketnummer für alle weiteren abfragen als ungültig markieren um doppeltes einchecken mit dem selben Ticket zu vermeiden
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Catering-Personal An- und Abmeldung
|Beschreibung                |Catering-Personal kann sich an den Verkaufsständen An- und Abmelden, um den Besuchern Essen zu verkaufen
|Akteure                     |Catering-Personal
|Auslöser                    |
|Voraussetzung               a|- Anmeldung: An dem Verkaufsstand ist ein freier Platz
|Essentielle Schritte        a|
- Anmeldung: Anmeldung über das Terminal
- Abmeldung: Abmeldung über das Terminal
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Catering: Verkauf von Getränken und Speisen
|Beschreibung                |Besucher könnene an einem Verkaufsstand Speisen und Getränke kaufen
|Akteure                     |Besucher, Catering-Personal
|Auslöser                    |Ein Besucher möchte etwas an einem Verkaufsstand kaufen
|Voraussetzung               |Das gewünschte Getränk/Essen ist noch auf Lager
|Essentielle Schritte        a|
1. Entnahme der zutaten aus dem Lager
2. evtl. Mitteilung an Festival-Leitung, wenn die Zutaten in zu geringen Mengen gelagert sind
3. Zubereitung der Bestellung
4. Verkauf
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Lager einsehen & Nachbestellung von Speisen und Getränken
|Beschreibung                |Der Festivalleiter kann den Lagerbestand prüfen und gegebenfalls neue Waren bestellen
|Akteure                     |Festivalleiter
|Auslöser                    |Der Festivalleiter möchte den Lagerbestand prüfen oder etwas nachbestellen
|Voraussetzung               |Der Festivalleiter ist am entsprechenden Terminal angemeldet
|Essentielle Schritte        a|
1. Abrufen des Lagerbestandes
2. evtl. Nachbestellung einer oder mehrerer Waren in beliebigen Mengen
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
|===
|ID                          |
|Name                        |Festivalleiter Status Abbruf
|Beschreibung                |Der Festivalleiter kann verschiedene Informationen über das Event an einem Terminal jederzeit abrufen
|Akteure                     |Festivalleiter
|Auslöser                    |Der Festivalleiter möchte Informationen über das Event
|Voraussetzung               |Der Festivalleiter ist am entsprechenden Terminal angemeldet
|Essentielle Schritte        |Abrufen der Informationen(Nachrichten von Mitarbeitern, Verkaufszahlen, Bühnenbelegung,...) an dem Terminal
|Erweiterungen               |
|Funktionale Anforderungen   |
|===

[cols="1h, 3"]
[[UC0001]]
|===
|ID                         |**<<UC0001>>**
|Name                       |Terminal für Festivalbesucher
|Beschreibung               |Festivalbesucher sollen sich am Terminal über Lageplan und Spielplan informieren können.
|Akteure                     |Festivalbesucher
|Auslöser                    |
_Öffnen des Festivalmanagers_: Wenn sich noch kein Mitarbeiter angemeldet hat werden Informationen zum Festival gezeigt

_Mitarbeiterlogout_: Wenn kein Mitarbeiter angemeldet ist werden Informationen zum Festival angezeigt
|Voraussetzung(en)           a|
siehe [Link zu Login]
|Essentielle Schritte           a|
1. Besuchermodus wird durch starten des Programms oder Logout eines Mitarbeiters aktiviert

2. Besucher kann Informationen über das Festival einsehen
|Erweiterungen                 |-
|Funktionale Anforderungen    |<<F0001>>
|===

[cols="1h, 3"]
[[UC0001]]
|===
|ID                         |**<<UC0001>>**
|Name                       |Line-Up planen
|Beschreibung               |Im Festivalmanager können Bands für bestimmte Bühnen und Zeiten gebucht werden.
|Akteure                     |Festivalleiter, Planungsabteilung
|Auslöser                    |
Ein Nutzer öffnet den "Personal und Künstler" Tab.
|Voraussetzung(en)           a|
Ein Nutzer mit Planungsberechtigungen ist eingeloggt.
|Essentielle Schritte           a|
1. Der "Personal und Künstler" Tab wird aufgerufen.

2. Von einer Liste von Künstlern können Angebote eingeholt werden

3. Aus den erhaltenen Angeboten können verschiedene Künstler ausgewählt werden,
denen anschließend eine Bühne und Zeit zugewiesen wird
|Erweiterungen                 |-
|Funktionale Anforderungen    |<<F0001>>
|===

[cols="1h, 3"]
[[UC0001]]
|===
|ID                         |**<<UC0001>>**
|Name                       |Lagelplan anpassen
|Beschreibung               |Im Festivalmanger kann eine Location für das Festival ausgewählt werden, auf dem Lageplan dieser Location können die Positionen von Bühnen, Catering, etc. angepasst werden.
|Akteure                     |Festivalleiter, Planungsabteilung
|Auslöser                    |
Ein Nutzer öffnet den "Lageplan" Tab.
|Voraussetzung(en)           a|
1. Ein Nutzer mit Planungsberechtigungen ist eingeloggt.

2. Das gewählte Festival hat noch nicht begonnen.
|Essentielle Schritte           a|
1. Location aus einer Liste buchen, falls noch nicht gebucht wurde.

2. Per Rechstklick auf Flächen im Lageplan auswählen, wofür diese Flächen genutzt werden (Bühne, Toilette, Catering, gesperrt)
|Erweiterungen                 |Location wechseln
|Funktionale Anforderungen    |<<F0001>>
|===

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

Dieser Abschnitt gibt einen Überblick über die funktionellen Anforderungen des Systems.

Die Tabelle enthält:

- Eine eindeutige Kennung der Anforderung (ID), die während des gesamten Projekts als Referenz verwendet werden kann.
- Die aktuelle Version der Anforderung, da Änderungen an einer Anforderung während des
     gesamten Projekts erfolgen können.

- Einen kurzen Namen der Anforderung.
- Die Beschreibung der Anforderung.


[options="header", cols="4h, 1, 2, 15"]
|===
|ID
|Version
|Name
|Beschreibung

|[[F00001]]<<F00001>>
|v0.1
|Authentification
a|
Das System muss in öffentlich zugängliche Teile und in Teile, die
für den Zugriff eine Authentifizierung erfordern, zerlegt werden
können. Wenn ein Benutzer im System vorhanden ist, muss er in
der Lage sein, sich zu authentifizieren, indem er die folgenden
Informationen angibt:

- Username
- Passwort

|[[F00002]]<<F00002>>
|v0.1
|Registration
a|
Das System muss einem nicht authentifizierten Benutzer
(<<F00001>>) die Möglichkeit bieten, sich nach dem Aufruf des
Navigationselements namens "Registrieren" zu registrieren

Die folgenden Informationen müssen angegeben werden:

- Username (eindeutig)
- Passwort
- Email-Adresse

Das System muss die bereitgestellten Daten validieren (<<F00003>>).
Der Benutzer muss im System als Kunde registriert sein und
muss sich nach erfolgreicher Validierung authentifizieren
(<<F00001>>) können.

|[[F00003]]<<F00003>>
|v0.1
|Validate  Registration
a|
Das System muss in der Lage sein, die bereitgestellten Daten
eines nichtregistrierten Benutzers zu validieren.
Die Eindeutigkeit des Benutzernamens muss gewährleistet sein.
Der Benutzer muss über jede Verletzung der Einschränkungen
informiert werden.


|[[F00004]]<<F00004>>
|v0.1
|Catalog
a|
Das System muss in der Lage sein, einen schreibgeschützten
Zugriff auf vorhandene Gelände und Bereiche über einen Katalog zu
ermöglichen.

|[[F00005]]<<F00005>>
|v0.1
|View Catalog
a|
Das System muss einem Benutzer die Möglichkeit bieten, den
Inhalt des Katalogs einzusehen.



|[[F00006]]<<F00006>>
|v0.1
| Add Order to Cart
a|
Das System muss einem Benutzer die Möglichkeit bieten, ein
ausgefülltes Formular zur Bestellung dem Warenkorb hinzuzufügen.

|[[F00007]]<<F00007>>
|v0.1
|Cart
a|
Das System muss jedem registrierten und authentifizierten
Benutzer einen Warenkorb zur Verfügung stellen, in dem er
ausgewählte Produkte zwischenspeichern kann. Der Warenkorb
muss temporär beständig und für jeden Benutzer einzigartig
sein.

|[[F00008]]<<F00008>>
|v0.1
| View Cart
a|
Das System muss einem Benutzer die Möglichkeit bieten, den
Inhalt des Warenkorbs zu authentifizieren.
Der Warenkorb muss folgende Angaben enthalten:

-
- Datum
- Eingefüllte Daten eines Festivals

|[[F00009]]<<F00009>>
|v0.1
| Buy in Cart
a|
Das System muss einem Benutzer die Möglichkeit bieten, mit den
Bestellungen im Warenkorb zur Kasse zu gehen und diese zu bezahlen.


|[[F00010]]<<F00010>>
|v0.1
|Orders
a|
Das System muss in der Lage sein, Bestelldaten  dauerhaft zu speichern.


|[[F00011]]<<F00011>>
|v0.1
|Create Order
a|
Das System muss in der Lage sein, eine Bestellung aus dem Inhalt
eines Warenkorbs zu erstellen.

Ein Auftrag muss mit dem Status "OFFEN" initialisiert werden.

|[[F00012]]<<F00012>>
|v0.1
|Pay Order
a|

|[[F00013]]<<F00013>>
|v0.1
| Archive Order
a|

Das System muss in der Lage sein, einen Auftrag zu archivieren.
Ein Auftrag wird archiviert, indem sein Status auf
"ABGESCHLOSSEN" gesetzt wird

|[[F00014]]<<F00014>>
|v0.1
|View Order
a|

as System muss einem Admin die Funktionalität zur Verfügung
stellen, alle Aufträge mit dem Status "ABGESCHLOSSEN"
einzusehen.
Die folgenden Informationen werden für jeden Auftrag
angezeigt:

- Zeitstempel der Erstellung
- Kunde, der den Auftrag erteilt hat
- Bezahlter Gesamtpreis der Bestellung


|[[F00015]]<<F00015>>
|v0.1
| Edit Profil
a|
Das System muss einem Benutzer die Möglichkeit bieten, sein Profil zu bearbeiten.

|[[F00016]]<<F00016>>
|v0.1
| Booking appointments
a|

Das System muss einem Planer die Möglichkeit bieten, Termine festzulegen und
die passende Location zu diesem Zeitpunkt zu buchen.

|[[F00017]]<<F00017>>
|v0.1
| Standortaufteilung
a|

Das System muss einem Planer die Funktionalität zur Verfügung
stellen, die  Location in verschiedene,
eindeutig gekennzeichnete Bereiche unterteilt(<<F00018>>).

|[[F00018]]<<F00018>>
|v0.1
| Kapazitätsbegrenzung
a|

Das System muss einem Planer  die Funktionalität zur Verfügung
stellen,   die  maximale Besucherzahl für einen Bereich der
Location zu ermitteln  und sich außerdem in
Camping-, Park-, Catering- und Stage-Bereiche einordnen




|[[F00019]]<<F00019>>
|v0.1
| Data Visualization
a|
Das System muss in der Lage sein, das Gelände und die Bereiche zu visualisieren.


|[[F00020]]<<F00020>>
|v0.1
| Änderungen vornehmen
a|
Das System muss einem Planer  die Funktionalität zur Verfügung
stellen, nachdem Location gebucht ist, können für dieses Festival Anpassungen durchgeführt werden, wie die
Bühnenpositionierung, Toilettenbestückung und Cateringstände.

|[[F00021]]<<F00021>>
|v0.1
| Ausrüstung mieten
a|
Das System muss einem Planer die Funktionalität zur Verfügung stellen,
Bühnen, Toilettenbestückung und Cateringstände von externen Anbietern zu mieten.

|[[F00022]]<<F00022>>
|v0.1
| Organisation
a|
Das System muss einem Planer die Möglichkeit bieten,  Angebote bei
verschiedenen Künstlern einzuholen, aus diesen Angeboten Künstler
auszuwählen, ein Spielplan für jede Bühne erstellt und Kartenpreis festzulegen.


|[[F00023]]<<F00023>>
|v0.1
| Statement of costs
a|
Das System muss in der Lage sein, eine automatische Kostenaufstellung
(Kosten für  Mieten, Gagen, Personal und Sonstigem)zur Verfügung zu erstellen.


|[[F00024]]<<F00024>>
|v0.1
|Overview
a|

Das System muss einem Admin die Übersicht bieten, welcher Mitarbeiter momentan am System angemeldet ist


|[[F00025]]<<F00025>>
|v0.1
| business data
a|
Das System muss einem Admin die Möglichkeit geben,
betriebswirtschaftliche Daten, wie Umsatz, Ausgaben,... , abzurufen und grafisch zu visualiseren.

|[[F00026]]<<F00026>>
|v0.1
|
a|





|===

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

[options="header", cols="4h, 1, 2, 15"]
|===

|ID
|Version
|Name
|Beschreibung


|[[F00023]]<<F00023>>
|v0.1
| Filter Catalog
a|
Das System sollte die Funktionalität bieten, den Katalog zu filtern
(z.B. nach Verfügbarkeit oder Datum).




|[[F00024]]<<F00024>>
|v0.1
|Edit Cart
a|
Das System sollte die Funktionalität bieten, den Warenkorb
ändern zu können.

Dies beinhaltet:

- Entfernen einzelner Produkte
- Änderung eines ausgefüllten Tippscheins




|===

== Nicht-Funktionale Anforderungen
Dieser Abschnitt wird einen Überblick über die nicht-funktionalen (NF) Anforderungen des
Projekts Festival Manager geben. Diese Anforderungen beschreiben, wie das System funktioniert und
innerhalb welcher Grenzen es funktionieren soll.

=== Qualitätsziele

Die folgende Tabelle zeigt, welche Qualitätsanforderungen in welchem Umfang erfüllt werden
müssen. In der ersten Spalte sind die Qualitätsanforderungen aufgelistet, während in den
folgenden Spalten ein "x" zur Kennzeichnung der Priorität verwendet wird.

1 = Nicht wichtig .. 5 = Sehr wichtig


[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Qualitätsanforderung           | 1 | 2 | 3 | 4 | 5
|Instandhaltbarkeit             |   |   | x |  |
|Benutzerfreundlichkeit         |   |   |   | x  |
|Benutzeroberfläche             |   |   |   |   | x
|Sicherheit                     |   |   |   |x  |
|===

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.


[options="header", cols="4h, 1, 2, 15"]
|===

|ID
|Version
|Name
|Beschreibung

|
|v0.1
| Verfügbarkeit-Laufzeit
a|as System muss mindestens 99,5% Laufzeit erreichen.

|
|v0.1
| Sicherheit - Passwort Speicherung
a| Passwörter von Benutzern dürfen nur als Hash-Werte
gespeichert werden, um Diebstahl zu verhindern.

|===

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
