= Test-Plan
Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
In diesem Dokument werden Unit- und Integrationstests für alle Komponenten der Software aufgelistet,
<<Zu testende Funktionalitäten, die getestet werden müssen>>.
Die Unit-Tests sollen den Entwicklern dabei helfen, Programmierfehler möglichst zeitig zu bemerken und sie zu beheben,
bevor der fehlerhafte Code in den Rest der Software eingebunden wird.
Mit den Integrationstests wird geprüft, ob die Komponenten der Software korrekt zusammenarbeiten.
Es wird außerdem darauf eingegangen, wie genau die Tests durchgeführt werden sollen.

Auch für den Auftraggeber kann dieses Dokument von Interesse sein,
weil es einige Anforderungen aus dem Pflichtenheft konkretisiert und
am Ende der Entwicklung als Abnahmetest dienen kann.
Die Benutzer der Software zählen nicht zur Zielgruppe des Test-Plans.

== Aufbau der Testbezeichner
Wir verwenden das Schema "Testtyp - Anwendungsfall - Nummer"
wobei Testtyp U für Unit-Tests und der Testtyp I für Integrationstests steht.
Die Nummer wird seperat für Integrations- und Unit-Tests von 1 hochgezählt

Also zum Beispiel U-AF001-1

== Test Gegenstände

[options="headers"]
|===
|Komponente |Test Gegenstände
|Festival a|
- Festival

- Location

- Schedule

- Map

- Equipment
|Catering a|
- Catering

- Catering Stock
|Planung a|
- Planning

- Offers

- Hire

- Renting
|Ticketshop a|
- Ticketshop
- Ticket
|Finanzen a| 
- FinancesController

- Finances

- Payment

- Income
|Nachrichten a|
|===

== Zu testende Funktionalitäten
Für alle großen Klassen sind Unit-Tests notwendig. Große Klassen sind zum Beispiel "Festival" und "FinancesController".
Nicht zu großen Klassen zählen zum Beispiel Repository Implementationen.

Zu testen ist außerdem das Zusammenspiel der Klassen innerhalb der Packages,
wofür es mehrere Integrationstests gibt. Die übgrigen Integrationstests sollen Fehler bei
der Integration seperater Packages deutlich machen.

== Nicht zu testende Funktionalitäten
Unit-Tests für die von uns verwendeten Bibliotheken von Drittanbietern (hauptsächlich salespoint, spring und javax) werden nicht durchgeführt.
Eigenständige Integrationstests für das Zusammenspiel mit Bibliotheksklassen sind nicht vorgesehen.
Stattdessen wird mit den Integrationstests für Komponenten auch geprüft, ob es Fehler bei der Integration der Bibliotheksklassen gibt. 

== Herangehensweise
Für Unit-Testfälle werden mit JUnit entsprechende Testklassen mit
Before-, After- und Test-Annotationen erstellt.

Die Integrationstests werden ebenfalls mit JUnit implementiert,
dabei wird das Bottom-Up Prinzip verwendet:
Es wird zuerst das zusammenspiel innerhalb der einzelnen Komponenten getestet,
dann werden die Komponeten miteinander getestet.

== Umgebungsvoraussetzungen
Die Tests werden mit JUnit und Maven durchgeführt. Spezielle Hardware oder Kommunikation über
Netzwerk oder Internet sind nicht notwendig.
Die für die Tests notwendigen Daten werden in die Testklassen einprogrammiert.

== Testfälle und Verantwortlichkeit
// See http://asciidoctor.org/docs/user-manual/#tables

[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe |Verantwortlicher
|U-AF011-1  |AF011              |
Das aktuell ausgewählte Festival kann 3000 Besucher haben              |
Anzahl Sicherheitskräfte: 10       |
Fehlermeldung wegen zu wenigen Sicherheitskräften   |Adrian, Tuan

|U-AF011-2  |AF011              |
Das aktuell ausgewählte Festival kann 3000 Besucher haben              |
Anzahl Sicherheitskräfte: 30       |
Anzahl Sicherheitskräfte wird auf 30 gesezt   |Adrian, Tuan

|U-AF012-1  |AF012              |
Das aktuell ausgewählte Festival kann 3000 Besucher haben              |
Vorraussichtlich verkaufte Tagestickets: 4000       |
Fehlermeldung wegen zu wenig verfügbaren Tickets   |Jan

|I-AF012-1  |AF012, AF010              |
Es wurden zwei Bühnen für 10000€ gebucht, ansonsten wurde kein Equipment gebucht             |
Öffnen der Finanzübersicht       |
Als Kosten für Equipment werden 20000€ angezeigt   |Jan, Adrian, Tuan

|I-AF014-2  |AF012, AF011              |
Es wurden Sicherheitskräfte gebucht die insgesamt Lohnkosten von 10000€ verursachen gebucht und sonst kein Personal gebucht             |
Öffnen der Finanzübersicht       |
Als Kosten für Personal werden 10000€ angezeigt   |Jan, Adrian, Tuan

|I-AF014-1  |AF014, AF001              ||
Der Preis für Camping-Tickets wird auf 200€ gesetzt       |
Ein ausgedruckte Camping-Ticket hat den Preis 200€ aufgedruckt   |Ahmad, Jan
|===
