= Zeiterfassung für Gruppe 04

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Ahmad |Jan |Adrian |Tuan |Georg |Robert |Meeting
|1  |220   |130   |230   |240    |150    |240   |90
|2  |235     |200   |360    |300    |200    |1600    |240
|3  |765   |840   |690   |720    |720    |1200    |170
|4  |790   |240    |840   |300    |300    |90    |95
|5  |865   |960    |1380   |800    |900    |200   |70
|6  |350   |240    |700   |1000    |450    |420    |50
|7  | 735   |600    |1100   |1000    |900    |1000  |70
|8  |563   |600    |900   |450    |720    |1000    |90    
|9  |890   |1000    |1700    |660    |960    |…    |180    
|10  |…   |240    |1260    |500    |…    |…    |105    
|11  |…   |…    |…    |…    |…    |…    |…    
|12  |…   |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
