= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:**

**Gruppe:**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Bei dem Praktikum habe ich neue Phasen gelernt, die zum Softwareentwicklung auch gehören.
Mit Spring Boot hat man viele Möglichkeiten, die beim Software hinzufügen kann und die sind seht hilfreich.
ich habe auch gelernt, mein eigenes Code zu testen und mit Junit hat man alles was er, um den Code zu testen braucht.
JPA hat unsere Arbeit um die Daten zu speichern leichter gemacht.


== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
* Die Kommunikation im Team war ganz gut sie waren immer hilfsbereit, ehrlich also damit hatten wir keine Probleme.
* Aufgabenverteilung was auch fair, jeder hat den Teil, der dafür interessiert.
* Was war verbesserungswürdig, das Frontend, es war okay aber könnten wir es noch verbessern.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?

* Schwierigkeiten bei Spring boot hat man zu wenig, da er einfach viele Lösungen im Internet finden kann und es ist ebenfalls dokumentiert.
* Beim Sales Point war es ein bisschen anderes, es gab nicht viele  Dokumentation dafür oder Beispiele,  auch wenn man Probleme hat, war es zeitaufwändig eine Lösung dafür zu finden.


== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
* Es wäre gut, wenn es ein Standard UML tool im Praktikum gab, da was wir  als UML tool benutzen haben, war es nicht ganz toll und altmodisch, da die andere tools waren nicht kostenfrei.
* Neue Aufgaben, die der aktuellen Entwicklung entsprechen.
* mehr Beispiele im VideoShop über SalesPoint.


== Feedback für den Tutor
* Der Tutor hat uns  immer versucht, Tasks mitzuteilen, damit wir auf dem Laufenden bleiben konnten.
* Hat unsere erledigte Tasks richtig gewertet und wenn wir Probleme hatten, war bereit zu helfen.

== Sonstiges und Anmerkungen
...