= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von:** 2

**Gruppe:** 04

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
- Softwareentwicklung ist nicht nur Programmieren, sondern auch:
Dokumentieren, Mit dem Team kommunizieren (!), Mit dem "Kunden" kommunizieren, Diagramme bauen etc. +
Diese Fähigkeiten muss man üben, genau so wie das Programmieren selbst
- Je eher man Unittests schreibt, desto eher findet man Fehler
- Ich wurde bestärkt in dem Wissen das Softwareentwicklung für mich kein attraktiver Beruf wäre
- IntelliJ IDEA ist eine sehr hilfreiche Entwicklungsumgebung

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
- Insgesamt hat die Zusammenarbeit gut funktioniert, obwohl die Gruppe deutlich größer ist als bspw. im Robolab hatten
wir keine großen Probleme uns auf Entscheidungen und Termine zu einigen
- Es war keine gute Idee, ein einzelnes Package für die gesamte Planung von Festivals zu haben,
da diese Package sehr umfangreich ist und die betroffenen Teammitglieder viel zu tun haben
- Es ist wichtig sich mit den Packages der anderen Teammitglieder auseinanderzusetzen
- Vor allem am Anfang der Implementierungsphase wäre noch mehr Kommunnikation zwischen Teammitgliedern gut gewesen

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
- Über Probleme in Java kann man sich oft sehr schnell per Stackoverflow etc. informieren.
Probleme in Spring und Thymeleaf zu verstehen ist dagegen sehr zeitaufwändig, man muss oft lange Texte lesen und viel ausprobieren
- Die Arbeit mit Maven und Junit war problemlos und sehr intuitiv,
möglicherweise auch weil diese Themen in der SWT-Vorlesung angesprochen wurden

== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
- Der Einstieg in Thymeleaf und das Spring Framework war sehr schwer,
eine Einführung zu diesen Themen in der SWT-Vorlesung oder in einem Sondermeeting mit dem Tutor wäre hilfreich gewesen
- Guestbook und Videoshop als erste Programmieraufgaben zu verwenden funktioniert gut
- Meines Wissens stand in früheren Jahrgängen eine MagicDraw Lizenz zur verfügung, eine solche Lizenz hätte uns sehr geholfen.
Es ist nicht einfach ein UML tool zu finden was kostenlos ist und für alle benötigten Diagrammtypen benutzt werden kann,
die vom Lehrstuhl empfohlenen Programme waren für uns nicht geeignet

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
- Tom hat flexibel auf unseren Fortschritt reagiert und
angemessene Deadlines und Kundenwünsche ausgesucht
- Die Konsultationen waren gut strukturiert,
wenn Gruppenmitglieder und Tutor unterschiedliche Meinungen hatten war es kein Problem diese zu diskutieren und eine Einigung zu finden
- Ich hatte den Eindruck, dass Kritik an Dokumentation und Software
immer direkt angesprochen und nicht zurückgehalten wurde, und das dabei auch Verbesserungsvorschläge besprochen wurden
- Auch Fragen außerhalb der Konsultationen wurden schnell beantwortet

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
/